### PR TITLE
added some basic logging

### PR DESCRIPTION
**Pull request by RohanJnr**
also added log files to git ignore

### CODE REVIEW

**Comment by RohanRadia** [comment]
Few changes needed:

In bot/__main__.py you need to miss a line between `import os` and `from datetime import datetime` remove the space between `from datetime import datetime` and `from discord.ext import commands`

**Comment by RohanRadia** [comment]
bot/__main__.py

You need to make a single `logger.info` statement instead of 3. Maybe just make it say something like:

`logger.info(f'Client logged in at {datetime.now()} as {self.user.name} ({self.user.id})')`

**Comment by RohanRadia** [comment]
bot/cogs/info.py

`import logging` and `import discord` should be together THEN there should be a space and then `from discord.ext import commands`

**Comment by RohanRadia** [comment]
bot/cogs/minigames.py

The original path that I put which was `with open(Path('resources', '8ball.json'), 'r', encoding="utf8") as f:` is actually correct if you take a look. Calling it as `with open(Path('bot', 'resources', '8ball.json'), 'r', encoding="utf8") as f:` which is what you have changed it to will cause an error.

**Comment by RohanRadia** [comment]
A couple of really minor things:

A) `logger.info('info cog loaded!')` - Can we make the I on Info capital?

B) Is it worth adding a `logger.info()` after each and every command to show us in the logs that command was run? That way we know that when an error occurs we know the command that was invoked before the error occurred. Up to you but I think maybe this would be useful?

**Comment by RohanJnr** [comment]
> 
> 
> bot/**main**.py
> 
> You need to make a single `logger.info` statement instead of 3. Maybe just make it say something like:
> 
> `logger.info(f'Client logged in at {datetime.now()} as {self.user.name} ({self.user.id})')`

i think it looks better and more readable in multiple lines

**Comment by RohanJnr** [comment]
> 
> 
> A couple of really minor things:
> 
> A) `logger.info('info cog loaded!')` - Can we make the I on Info capital?
> 
> B) Is it worth adding a `logger.info()` after each and every command to show us in the logs that command was run? That way we know that when an error occurs we know the command that was invoked before the error occurred. Up to you but I think maybe this would be useful?

it will be useful to add info logging whenever a cmd is used but id say add it to a few commands only.Like commands which changes some configuration, a http request, etc.

**Pull request merged**
